import os, json, argparse, random
from datetime import datetime, timedelta
from PIL import Image
import hashlib
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from tqdm.auto import tqdm
from transformers import CLIPModel, CLIPProcessor
from utils import *
device = "cuda" if torch.cuda.is_available() else "cpu"
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

CACHE_DIR = "cache_embeddings_retrieval"
os.makedirs(CACHE_DIR, exist_ok=True)


def build_split_infos(dataset, split):
    """
    Returns list of (img_path, img_url) for the chosen split.
    """
    if dataset=='tara':
        split_file = f"data/TARA_dataset/input/gold_{split}.jsonl"
        entries = load_jsonl(split_file)
        for i, x in enumerate(entries):
            x["orig_idx"] = i
        img_infos = [(f"data/TARA_dataset/img/{split}/{x['orig_idx']}.png", x["web_url"]) for x in entries]
    else:
        #5pils-OOC
        split_file = 'data/5pils_ooc/test.json'
        entries = load_json(split_file)[::2]
        img_infos =  [(f"data/5pils_ooc/{d['image_path']}", d['URL']) for d in entries]
    return img_infos


def build_articles_and_maps(dataset="tara"):
    articles = []
    processed_articles_dir = "data/processed_articles"
    qwen_class_dir = "data/qwen2.5_article_class"
    caption_paths = ["data/qwen2.5_caption_gt", "data/qwen2.5_caption"]
    for f in sorted(os.listdir(processed_articles_dir)):
        if dataset=='tara':
            #Only remove 2022, 2023, and Guardian part 2 if it is TARA
            if ('2022' in f) or ('2023' in f) or ('guardian_part2' in f) :
                continue
        if f.endswith(".json"):
            articles += load_json(os.path.join(processed_articles_dir, f))
    # qwen2.5 category 1 filter
    qwen_class = []
    for f in sorted(os.listdir(qwen_class_dir)):
        if dataset=='tara':
            if ('2022' in f) or ('2023' in f) or ('guardian_part2' in f):
                continue
        if f.endswith(".json"):
            qwen_class += load_json(os.path.join(qwen_class_dir, f))
    qwen_class = {q['web_url']:q['output'][0]  for q in qwen_class}
    # keep only category 1
    articles = [articles[a] for a in range(len(articles)) if qwen_class[articles[a]['web_url']].lower()=='category 1']
    articles = [a for a in articles if 'glocations' in [kw['name'].lower() for kw in a['keywords']]]
    articles += load_json('data/tara_articles/train.json')
    articles_urls_set = set([a['web_url'] for a in articles])
    #Load news image captions generated by qwen2.5
    captions = []
    for path in caption_paths:
        for file in os.listdir(f"{path}/news_image_caption/"):
            captions += load_json(os.path.join(f"{path}/news_image_caption/",file))

    captions = [c for c in captions if c['web_url'] in articles_urls_set]
    web_urls= [c['web_url'] for c in captions for _ in range(min(len(c['output']), 1))]
    article_caption_indices = {}
    for idx, url in enumerate(web_urls):
        article_caption_indices.setdefault(url, []).append(idx)

    # web_url -> first caption
    url2cap = {}
    for c in captions:
        url = c.get("web_url")
        outs = c.get("output") or []
        if url and outs and outs[0].strip():
            url2cap[url] = outs[0]

    # keep only articles that have a caption
    articles = [a for a in articles if a.get("web_url") in url2cap]

    # build glocations text
    url2loc_text = {}
    for a in articles:
        url = a.get("web_url")
        kws = a.get("keywords", []) or []
        locs = [clean(k.get("value", "")) for k in kws
                if clean(k.get("name", "")).lower() == "glocations" and k.get("value")]
        locs = [x for x in dict.fromkeys(locs) if x]
        if locs:
            url2loc_text[url] = " ; ".join(locs)

    # final set: must have caption and at least one glocation
    valid = sorted(set(url2cap.keys()) & set(url2loc_text.keys()))
    url2cap = {u: url2cap[u] for u in valid}
    url2loc_text = {u: url2loc_text[u] for u in valid}
    url2date = {}
    for a in articles:
        u = a.get("web_url")
        if u in url2cap:
            d = a.get("pub_date")
            if isinstance(d, str) and len(d) >= 10:
                url2date[u] = d[:10]

    return url2cap, url2loc_text, url2date


def load_url2caps(caption_roots, allowed_urls):
    caps = []
    for path in caption_roots.split('-'):
        p = os.path.join(path, "news_image_caption")
        if not os.path.isdir(p):
            continue
        for file in os.listdir(p):
            if file.endswith(".json"):
                caps += load_json(os.path.join(p, file))

    url2caps = {}
    for c in caps:
        url = c.get("web_url")
        if url not in allowed_urls:
            continue
        outs = c.get("output") or []
        texts = [t.strip() for t in outs if isinstance(t, str) and t.strip()]
        if texts:
            url2caps[url] = texts[:1]
    return url2caps


# Cache utilities
def _safe(s):
    return "".join(ch if ch.isalnum() or ch in "._-+" else "_" for ch in s)

def _ckpt_tag(base_ckpt, biencoder_ckpt):
    b = _safe(base_ckpt)
    be = _safe(biencoder_ckpt or "base_model")
    return f"{b}__{be}"

def _hash_list(items):
    h = hashlib.sha1()
    for it in items:
        h.update(it.encode("utf-8"))
        h.update(b"\n")
    return h.hexdigest()[:12]

def _cache_paths(kind, tag, list_hash):
    root = os.path.join(CACHE_DIR, kind, tag)
    os.makedirs(root, exist_ok=True)
    return os.path.join(root, f"{list_hash}.pt"), os.path.join(root, f"{list_hash}.json")

def _save_feats_and_index(tensor, items, kind, tag):
    hh = _hash_list(items)
    pt_path, js_path = _cache_paths(kind, tag, hh)
    torch.save(tensor, pt_path)
    save_json({"items": items}, js_path)
    return pt_path, js_path

def _load_feats_and_index(items, kind, tag):
    hh = _hash_list(items)
    pt_path, js_path = _cache_paths(kind, tag, hh)
    if os.path.isfile(pt_path) and os.path.isfile(js_path):
        meta = load_json(js_path)
        if meta.get("items") == items:
            feats = torch.load(pt_path, map_location="cpu")
            return feats
    return None


def _ce_tag(base_ckpt, cross_head_ckpt):
    b = _safe(base_ckpt)
    h = _safe(cross_head_ckpt or "ce_head")
    return f"{b}__{h}"

def _ce_pair_cache_path(img_path, ce_tag):
    """One JSON file per image, contains { loc_text -> prob } for this CE ckpt tag."""
    img_key = hashlib.sha1(img_path.encode("utf-8")).hexdigest()[:16]
    folder = os.path.join(CACHE_DIR, "ce_pair_scores", ce_tag)
    os.makedirs(folder, exist_ok=True)
    return os.path.join(folder, f"{img_key}.json")


# Encoders (+ caching for frozen/bi)
@torch.no_grad()
def encode_texts_list_cached(clip, texts, processor, tag_prefix, kind = "cap_feats", bs= 256):
    items = list(texts)
    cached = _load_feats_and_index(items, kind, tag_prefix)
    if cached is not None:
        return cached
    feats = []
    for s in tqdm(range(0, len(texts), bs), desc=f"encode {kind}"):
        batch = processor(text=texts[s:s+bs], return_tensors="pt", padding=True, truncation=True).to(device)
        emb = clip.get_text_features(**batch).float().cpu()
        feats.append(emb)
    X = F.normalize(torch.cat(feats, dim=0), dim=-1)
    _save_feats_and_index(X, items, kind, tag_prefix)
    return X


def prepare_multi_caps_index(url2caps):
    """
    Flatten per-URL captions to a single list and build an index tensor to aggregate MAX per article.
    """
    owner_urls = sorted(url2caps.keys())
    flat_caps = []
    idx_lists = []

    for u in owner_urls:
        caps = url2caps[u][:1]
        cur = []
        for cap in caps:
            cur.append(len(flat_caps))
            flat_caps.append(cap)
        idx_lists.append(cur)

    A = len(owner_urls)
    M = max((len(v) for v in idx_lists), default=1)
    idx_mat = torch.full((A, M), -1, dtype=torch.long)
    for a_idx, lst in enumerate(idx_lists):
        for j, flat_idx in enumerate(lst):
            idx_mat[a_idx, j] = flat_idx
    return owner_urls, flat_caps, idx_mat


@torch.no_grad()
def encode_caps_cached(clip, urls, url2cap, processor, base_ckpt, biencoder_ckpt):
    tag = _ckpt_tag(base_ckpt, biencoder_ckpt)
    urls_sorted = list(urls)
    cached = _load_feats_and_index(urls_sorted, "cap_feats", tag)
    if cached is not None:
        return cached, urls_sorted
    feats = []
    bs = 256
    for s in tqdm(range(0, len(urls_sorted), bs), desc="encode captions"):
        texts = [url2cap[u] for u in urls_sorted[s:s+bs]]
        batch = processor(text=texts, return_tensors="pt", padding=True, truncation=True).to(device)
        emb = clip.get_text_features(**batch).float().cpu()
        feats.append(emb)
    feats = F.normalize(torch.cat(feats, dim=0), dim=-1)
    _save_feats_and_index(feats, urls_sorted, "cap_feats", tag)
    return feats, urls_sorted


@torch.no_grad()
def encode_imgs_cached(clip, img_paths, processor, base_ckpt, biencoder_ckpt, split_tag):
    tag = _ckpt_tag(base_ckpt, biencoder_ckpt) + f"__{_safe(split_tag)}"
    cached = _load_feats_and_index(img_paths, "img_feats", tag)
    cached = None
    if cached is not None:
        return cached, img_paths
    feats = []
    bs = 64
    for s in tqdm(range(0, len(img_paths), bs), desc="encode images"):
        paths = img_paths[s:s+bs]
        imgs = [Image.open(p).convert("RGB") for p in paths]
        batch = processor(images=imgs, return_tensors="pt").to(device)
        emb = clip.get_image_features(**batch).float().cpu()
        feats.append(emb)
    feats = F.normalize(torch.cat(feats, dim=0), dim=-1)
    _save_feats_and_index(feats, img_paths, "img_feats", tag)
    return feats, img_paths

# -------------------------
# Cross-encoder head
# -------------------------
class CrossEncMLP(nn.Module):
    def __init__(self, 
                 clip_base, 
                 hidden=[256],  
                 operations="concatenation"):
        super().__init__()
        self.clip = clip_base
        self.operations = operations

        # freeze all
        for p in self.clip.parameters():
            p.requires_grad = False

        D = self.clip.config.projection_dim
        # input dim: 2D for "concatenation" (img || txt), +D for each of "multiplication" and "difference"
        in_dim = 0
        if "concatenation" in self.operations:
            in_dim += 2 * D
        if "multiplication" in self.operations:
            in_dim += D
        if "difference" in self.operations:
            in_dim += D

        layers = [nn.Linear(in_dim, hidden[0]), nn.GELU()]
        layers.append(nn.Linear(hidden[0], 1))
        self.head = nn.Sequential(*layers)

    def forward(self, pixel_values, input_ids, attention_mask):
        img_emb = F.normalize(self.clip.get_image_features(pixel_values=pixel_values), dim=-1)
        txt_emb = F.normalize(self.clip.get_text_features(input_ids=input_ids, attention_mask=attention_mask), dim=-1)

        pieces = []
        if "concatenation" in self.operations:
            pieces += [img_emb, txt_emb]
        if "multiplication" in self.operations:
            pieces.append(img_emb * txt_emb)
        if "difference" in self.operations:
            pieces.append((img_emb - txt_emb).abs())

        feat = torch.cat(pieces, dim=-1)
        return self.head(feat).squeeze(1)
    

def _ce_build_features(img_emb, txt_emb, operations):
    """
    Build CE feature vector according to operations:
      - 'concatenation' -> [img, txt]
      - 'multiplication' -> img*txt
      - 'difference' -> |img-txt|
    """
    ops = set(operations.split("-")) if isinstance(operations, str) else set(operations)
    pieces = []
    if "concatenation" in ops:
        pieces += [img_emb, txt_emb]
    if "multiplication" in ops:
        pieces.append(img_emb * txt_emb)
    if "difference" in ops:
        pieces.append((img_emb - txt_emb).abs())
    if not pieces: 
        pieces = [img_emb, txt_emb]
    return torch.cat(pieces, dim=-1)



@torch.no_grad()
def ce_probs_pairs_cached(
    clip_ce, ce_head, processor,
    img_path,
    loc_texts,
    base_ckpt,
    cross_head_ckpt,
    operations = "concatenation",
    bs = 128
):
    tag = _ce_tag(base_ckpt, cross_head_ckpt)
    cache_file = _ce_pair_cache_path(img_path, tag)
    cache = {}
    needed = [t for t in loc_texts if t not in cache]
    if needed:
        img = Image.open(img_path).convert("RGB")
        for s in range(0, len(needed), bs):
            chunk = needed[s:s+bs]
            batch = processor(
                images=[img]*len(chunk),
                text=[f"An image from {t}" for t in chunk],
                return_tensors="pt", padding=True, truncation=True
            ).to(device)
            img_emb = F.normalize(clip_ce.get_image_features(pixel_values=batch["pixel_values"]), dim=-1)
            txt_emb = F.normalize(clip_ce.get_text_features(input_ids=batch["input_ids"], attention_mask=batch["attention_mask"]), dim=-1)
            feat = _ce_build_features(img_emb, txt_emb, operations)
            logits = ce_head(feat).squeeze(1)
            probs = torch.sigmoid(logits).float().cpu().numpy().tolist()
            for t, p in zip(chunk, probs):
                cache[t] = float(p)
        save_json(cache, cache_file)
    return [float(cache[t]) for t in loc_texts]


@torch.no_grad()
def ce_probs_texts_cached(
    clip_ce, ce_head, processor,
    img_path,
    texts,
    base_ckpt,
    cross_head_ckpt,
    operations = "concatenation",
    bs = 128
):
    tag = _ce_tag(base_ckpt, cross_head_ckpt)
    cache_file = _ce_pair_cache_path(img_path, tag)
    cache = {}
    needed = [t for t in texts if t not in cache]
    if needed:
        img = Image.open(img_path).convert("RGB")
        for s in range(0, len(needed), bs):
            chunk = needed[s:s+bs]
            batch = processor(
                images=[img]*len(chunk),
                text=chunk,
                return_tensors="pt", padding=True, truncation=True
            ).to(device)
            img_emb = F.normalize(clip_ce.get_image_features(pixel_values=batch["pixel_values"]), dim=-1)
            txt_emb = F.normalize(clip_ce.get_text_features(input_ids=batch["input_ids"], attention_mask=batch["attention_mask"]), dim=-1)
            feat = _ce_build_features(img_emb, txt_emb, operations)
            logits = ce_head(feat).squeeze(1)
            probs = torch.sigmoid(logits).float().cpu().numpy().tolist()
            for t, p in zip(chunk, probs):
                cache[t] = float(p)
        save_json(cache, cache_file)
    return [float(cache[t]) for t in texts]



def _build_time_clusters_from_pool(pool_urls,  url2loc_text, url2date,
                                   Nmin=2, window_days=15,
                                   allowed_tokens = None):
    """
    pool_urls: list[str] top-K urls from BI
    allowed_tokens: if provided, only clusters whose shared token in allowed_tokens are allowed.
    """
    # per-url info
    def _parse(d): return datetime.fromisoformat(d).date()
    info = {}
    for u in pool_urls:
        if u not in url2loc_text or u not in url2date:
            continue
        info[u] = {
            "date": _parse(url2date[u]),
            "tokens": extract_loc_atoms(url2loc_text[u])
        }
    if not info:
        return []

    token2urls = {}
    for u, d in info.items():
        for t in d["tokens"]:
            if allowed_tokens is not None and t not in allowed_tokens:
                continue
            token2urls.setdefault(t, []).append(u)

    clusters, seen = [], set()
    for token, urls in token2urls.items():
        if len(urls) < Nmin:
            continue
        urls_sorted = sorted(urls, key=lambda x: info[x]["date"])
        left = 0
        for right in range(len(urls_sorted)):
            while info[urls_sorted[right]]["date"] - info[urls_sorted[left]]["date"] > timedelta(days=window_days):
                left += 1
            if right - left + 1 >= Nmin:
                group = urls_sorted[left:right+1]
                key = tuple(sorted(group))
                if key in seen:
                    continue
                seen.add(key)
                dmin, dmax = info[group[0]]["date"], info[group[-1]]["date"]

                text = f"An image taken between {dmin.isoformat()} and {dmax.isoformat()} in {token}"
                clusters.append({
                    "urls": group,
                    "token": token,
                    "dmin": dmin.isoformat(),
                    "dmax": dmax.isoformat(),
                    "text": text
                })
    return clusters

# -------------------------
# Core methods
# -------------------------
@torch.no_grad()
def run_frozen_or_bi(method, img_infos, url2caps, top_k, base_ckpt, biencoder_ckpt, split):
    """
    Frozen or bi-encoder retrieval with multi-caption support per article.
    Similarity(image, article) = MAX over the article's selected captions.
    """
    clip = CLIPModel.from_pretrained(base_ckpt).to(device)
    if method == "biencoder" and biencoder_ckpt and biencoder_ckpt != "base_model":
        state = torch.load(f"clip_model/{biencoder_ckpt}", map_location=device)
        clip.load_state_dict(state, strict=False)
    clip.eval()
    processor = CLIPProcessor.from_pretrained(base_ckpt)

    # Prepare per-article captions
    owner_urls, flat_caps, idx_mat = prepare_multi_caps_index(url2caps)
    # Encode captions
    tag_prefix = _ckpt_tag(base_ckpt, biencoder_ckpt) + f"__{_safe(split)}"
    cap_feats = encode_texts_list_cached(clip, flat_caps, processor, tag_prefix, kind="cap_feats", bs=256)  
    # Encode images
    img_paths = [p for p, _ in img_infos]
    img_feats, _ = encode_imgs_cached(clip, img_paths, processor, base_ckpt, biencoder_ckpt, split)     

    sims_caps = img_feats @ cap_feats.T  
    idx_mat_dev = idx_mat.to(sims_caps.device)
    idx_clamped = idx_mat_dev.clamp(min=0)                 
    mask = (idx_mat_dev >= 0)                              

    mapping = {}
    for i, img_path in enumerate(img_paths):
        row = sims_caps[i]                               
        gathered = row[idx_clamped]                    
        gathered = gathered.masked_fill(~mask, float("-inf"))
        per_article = gathered.max(dim=1).values          

        k = min(top_k, per_article.numel())
        vals, art_idxs = torch.topk(per_article, k=k)
        urls = [owner_urls[j] for j in art_idxs.tolist()]
        mapping[img_path] = urls

    return mapping, processor, clip, owner_urls, cap_feats


@torch.no_grad()
def run_bi_then_time_ce_cluster_rerank(
    img_infos,
    url2cap, url2loc_text, url2date,
    *,
    base_ckpt,
    biencoder_ckpt,
    cross_head_ckpt,
    split = "dev",
    top_k = 100,
    cluster_N = 2,
    cluster_window_days = 15,
    dropout= 0.0,
    operations = "concatenation-multiplication-difference",
    min_clusters = 2
):
    """
    BI top-K -> detect clusters (shared token + <=window_days span)
      - If >=min_clusters clusters of size >= N: score clusters with CE, order clusters by CE desc,
        and within each cluster keep BI order; after clusters, append non-clustered URLs by BI.
      - Else: return pure BI order.
    """
    # BI encoder (+ caches)
    clip_bi = CLIPModel.from_pretrained(base_ckpt).to(device)
    if biencoder_ckpt and biencoder_ckpt != "base_model":
        state = torch.load(f"clip_model/{biencoder_ckpt}", map_location=device)
        clip_bi.load_state_dict(state, strict=False)
    clip_bi.eval()
    processor = CLIPProcessor.from_pretrained(base_ckpt)

    corpus_urls = sorted(url2cap.keys())
    cap_feats, cap_ids = encode_caps_cached(clip_bi, corpus_urls, url2cap, processor, base_ckpt, biencoder_ckpt)
    img_paths = [p for p, _ in img_infos]
    img_feats, _ = encode_imgs_cached(clip_bi, img_paths, processor, base_ckpt, biencoder_ckpt, split)
    sims = img_feats @ cap_feats.T

    # CE head
    clip_ce = None
    ce = None
    if cross_head_ckpt:
        clip_ce = CLIPModel.from_pretrained(base_ckpt).to(device)
        clip_ce.eval()
        ce = CrossEncMLP(clip_ce, hidden=[256], dropout=dropout, operations=operations).to(device)
        ce.head.load_state_dict(torch.load(f"clip_model/{cross_head_ckpt}", map_location=device))
        ce.eval()

    results = {}
    for i, (img_path, _) in enumerate(tqdm(img_infos, desc="BI->TimeCE cluster rerank")):
        vals, idxs = torch.topk(sims[i], k=min(top_k, sims.shape[1]))
        pool_urls = [cap_ids[j] for j in idxs.tolist()]
        pool_bi   = [float(v) for v in vals.tolist()]

        # Build clusters from top-K pool
        clusters = _build_time_clusters_from_pool(
            pool_urls, url2loc_text, url2date,
            Nmin=cluster_N, window_days=cluster_window_days
        )

        # If fewer than mininimum cluster, keep BI order
        if len(clusters) < min_clusters or ce is None: 
            results[img_path] = pool_urls
            continue

        # Score clusters with CE using their text ("An image taken between ... in TOKEN")
        cluster_texts = [c["text"] for c in clusters]
        ce_probs = ce_probs_texts_cached(
            clip_ce=clip_ce, ce_head=ce.head, processor=processor,
            img_path=img_path, texts=cluster_texts,
            base_ckpt=base_ckpt, cross_head_ckpt=cross_head_ckpt, operations=operations, bs=128
        )
        # Order clusters by CE prob desc
        order_clusters = sorted(range(len(clusters)), key=lambda k: ce_probs[k], reverse=True)
        # Map url -> BI score
        bi_map = {u: s for u, s in zip(pool_urls, pool_bi)}

        used = set()
        ranked = []
        #  pick exactly ONE best-BI article per cluster, in CE order
        rep_urls = []
        for k in order_clusters:
            urls_block = clusters[k]["urls"]
            if not urls_block: 
                continue
            best_u = max(urls_block, key=lambda u: bi_map.get(u, 0.0))
            if best_u not in used:
                rep_urls.append(best_u)
                used.add(best_u)

        ranked.extend(rep_urls)
        #  append the rest by original BI order
        for u in sorted(pool_urls, key=lambda u: bi_map.get(u, 0.0), reverse=True):
            if u not in used:
                ranked.append(u); used.add(u)

        results[img_path] = ranked[:len(pool_urls)]

    return results


@torch.no_grad()
def run_bi_then_ce_mul_rerank(
    img_infos,
    url2cap, url2loc_text,
    top_k,
    base_ckpt,
    biencoder_ckpt,
    cross_head_ckpt,
    split = "dev",
    dropout = 0.0,
    operations = "concatenation-multiplication-difference"
):
    """
    1) Retrieve top-K with BI encoder on captions
    2) Re-rank those K by CE_prob * BI_score
    Returns: dict img_path -> [urls sorted by (CE*BI) desc]
    """
    # BI encoder (+ caches)
    clip_bi = CLIPModel.from_pretrained(base_ckpt).to(device)
    if biencoder_ckpt and biencoder_ckpt != "base_model":
        state = torch.load(f"clip_model/{biencoder_ckpt}", map_location=device)
        clip_bi.load_state_dict(state, strict=False)
    clip_bi.eval()
    processor = CLIPProcessor.from_pretrained(base_ckpt)

    corpus_urls = sorted(url2cap.keys())
    cap_feats, cap_ids = encode_caps_cached(clip_bi, corpus_urls, url2cap, processor, base_ckpt, biencoder_ckpt)
    img_paths = [p for p, _ in img_infos]
    img_feats, _ = encode_imgs_cached(clip_bi, img_paths, processor, base_ckpt, biencoder_ckpt, split)

    # CE model (end-to-end, pairwise cached)
    clip_ce = CLIPModel.from_pretrained(base_ckpt).to(device)
    clip_ce.eval()
    ce = CrossEncMLP(clip_ce, hidden=[256], dropout=dropout, operations=operations).to(device)
    ce.head.load_state_dict(torch.load(f"clip_model/{cross_head_ckpt}", map_location=device))
    ce.eval()

    sims = img_feats @ cap_feats.T 
    results = {}
    for i, (img_path, _) in enumerate(tqdm(img_infos, desc="BI->CE mul rerank")):
        vals, idxs = torch.topk(sims[i], k=min(top_k, sims.shape[1]))
        cand_urls = [cap_ids[j] for j in idxs.tolist()]
        bi_scores = vals.tolist()

        loc_texts = [url2loc_text[u] for u in cand_urls]
        ce_probs = ce_probs_pairs_cached(
            clip_ce=clip_ce, ce_head=ce.head, processor=processor,
            img_path=img_path, loc_texts=loc_texts,
            base_ckpt=base_ckpt, cross_head_ckpt=cross_head_ckpt, operations = operations, bs=128
        )
        combined = [float(b) * float(c) for b, c in zip(bi_scores, ce_probs)]
        order = sorted(range(len(cand_urls)), key=lambda t: combined[t], reverse=True)
        results[img_path] = [cand_urls[t] for t in order]
    return results


# Main
def main(args):
    random.seed(args.seed)
    img_infos = build_split_infos(args.dataset, args.split)
    url2cap, url2loc_text, url2date = build_articles_and_maps(args.dataset)
    all_urls= sorted(url2cap.keys())


    url2cap       = {u: url2cap[u]       for u in all_urls if u in url2cap}
    url2loc_text  = {u: url2loc_text[u]  for u in all_urls if u in url2loc_text}
    url2date      = {u: url2date.get(u)  for u in all_urls if u in url2date}
    allowed_urls = set(url2cap.keys())
    url2caps = load_url2caps(args.caption_roots, allowed_urls) 

    if args.method in ("frozen_clip", "biencoder"):
        results, _, _, _, _ = run_frozen_or_bi(
            args.method, img_infos, url2caps, args.top_k,
            args.base_ckpt, args.biencoder_ckpt, args.split
        )
    elif args.method == "biencoder_then_ce_mul_rerank":
        results = run_bi_then_ce_mul_rerank(
            img_infos=img_infos,
            url2cap=url2cap, url2loc_text=url2loc_text,
            top_k=args.top_k,
            base_ckpt=args.base_ckpt,
            biencoder_ckpt=args.biencoder_ckpt,
            cross_head_ckpt=args.ce1_ckpt,
            split=args.split,
            dropout=args.dropout,
            operations=args.operations
        )

    elif args.method == "biencoder_then_time_ce_cluster_rerank":
        results = run_bi_then_time_ce_cluster_rerank(
            img_infos=img_infos,
            url2cap=url2cap, url2loc_text=url2loc_text, url2date=url2date,
            base_ckpt=args.base_ckpt,
            biencoder_ckpt=args.biencoder_ckpt,
            cross_head_ckpt=args.ce2_ckpt,
            split=args.split,
            top_k=args.top_k,
            cluster_N=args.cluster_N,
            cluster_window_days=args.cluster_window_days,
            dropout=args.dropout,
            operations=args.operations,
            min_clusters=args.min_clusters
        )
    else:
        raise SystemExit(f"Unknown method: {args.method}")
        
    #save results
    root = 'retrieval_results'
    os.makedirs(root, exist_ok=True)
    root = f"{root}/{args.method}"
    os.makedirs(root, exist_ok=True)
    if args.method=="frozen_clip":
        path = f"{root}/{args.dataset}_{args.split}_topK{args.top_k}.json"
    elif args.method=="biencoder":
        path = f"{root}/{args.dataset}_{args.split}_topK{args.top_k}_{args.biencoder_ckpt}.json"
    elif args.method == "biencoder_then_ce_mul_rerank":
        path = f"{root}/{args.dataset}_{args.split}_topK{args.top_k}_{args.biencoder_ckpt}_{args.ce1_ckpt}_mul_{args.seed}.json"
    elif args.method == "biencoder_then_time_ce_cluster_rerank":
        tag = f"topK{args.top_k}_{args.biencoder_ckpt}_{args.ce2_ckpt}_N{args.cluster_N}_W{args.cluster_window_days}_min_clusters{args.min_clusters}"
        path = f"{root}/{args.dataset}_{args.split}_{tag}_{args.seed}.json"
    else:
        tag = f"topK{args.top_k}_L{args.topL}_N{args.cluster_N}_W{args.cluster_window_days}_minC{args.min_clusters}_{args.biencoder_ckpt}_{args.ce1_ckpt}_{args.ce2_ckpt}"
        path = f"{root}/{args.dataset}_{args.split}_{tag}_{args.seed}.json"   
    with open(path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=4)
    print(f"Saved: {path}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--method", choices=["frozen_clip", "biencoder", "biencoder_then_ce_mul_rerank","biencoder_then_time_ce_cluster_rerank"], required=True)
    ap.add_argument("--dataset", choices=["tara", "5pils_ooc"], default = "tara")
    ap.add_argument("--split", choices=["dev", "test", "interest"], default="dev")
    ap.add_argument("--task", choices=["time", "location"])

    # encoders
    ap.add_argument("--base_ckpt", default="openai/clip-vit-large-patch14") 
    ap.add_argument("--biencoder_ckpt", default="bi_encoder.pt") 
    ap.add_argument("--ce1_ckpt", default="cross_encoder_location.pt", help="Cross-encoder #1 ckpt (location scoring)")
    ap.add_argument("--ce2_ckpt", default="cross_encoder_event.pt", help="Cross-encoder #2 ckpt (event scoring)")
    ap.add_argument("--operations", type=str, default="concatenation",
                    help="Use '-' to combine: concatenation-multiplication-difference")
    ap.add_argument("--top_k", type=int, default=100)

    # time cluster
    ap.add_argument("--cluster_N", type=int, default=3, help="Min cluster size for time CE rerank")
    ap.add_argument("--cluster_window_days", type=int, default=15, help="Max time span per cluster (days)")
    ap.add_argument("--min_clusters",type=int, default=2, help="Minimum number of clusters in top 100 results to consider doing reranking")

    ap.add_argument("--seed", default=123, type = int, choices=[123,456,789])

    args = ap.parse_args()
    random.seed(args.seed)
    np.random.seed(args.seed)
    main(args)
